networks:
  card:
    driver: bridge

volumes:
  pg_data: null
  pycache: null

services:
  web:
    env_file:
      - .env
    networks:
      - card
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    container_name: test_web
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
      - SCRIPT=${SCRIPT:-entrypoint.sh}
    volumes:
      - pycache:/var/cache/pycache
    depends_on:
      - db
      - redis
  db:
    networks:
      - card
    image: postgres:16
    restart: always
    container_name: test_db
    environment:
      POSTGRES_DB: ${DB_NAME:-django}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-2309}
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    container_name: test_redis
    networks:
      - card
    restart: always

    image: redis
