networks:
  card:
    driver: bridge

volumes:
  pg_data: null
  pycache: null

services:
  nginx:
    
    networks:
      - card
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - web
  web:
    env_file:
      - .env
    networks:
      - card
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
      - SCRIPT=${SCRIPT:-entrypoint.sh}
    volumes:
      - .:/code
      - pycache:/var/cache/pycache
    depends_on:
      - db
      - redis
  db:
    networks:
      - card
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-django}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-2309}
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    networks:
      - card
    restart: always

    image: redis
